"""Record only the installed runtime/test dependency closure, not host utilities."""
import importlib.metadata as metadata
from pathlib import Path
from packaging.requirements import Requirement
from packaging.utils import canonicalize_name


def main():
    pending = ["numpy", "pandas", "pydicom", "scikit-image", "scikit-learn", "tensorflow", "pytest", "setuptools", "wheel"]
    versions = {}
    while pending:
        name = canonicalize_name(pending.pop())
        if name in versions:
            continue
        distribution = metadata.distribution(name)
        versions[name] = distribution.version
        for raw in distribution.requires or []:
            requirement = Requirement(raw)
            if requirement.marker is None or requirement.marker.evaluate({"extra": ""}):
                pending.append(requirement.name)
    text = "# Tested Windows, Python 3.12 dependency closure; generated by audit/lock_environment.py\n"
    text += "\n".join(f"{name}=={version}" for name, version in sorted(versions.items()))+"\n"
    Path("requirements-lock.txt").write_text(text, encoding="utf-8")


if __name__ == "__main__":
    main()
